server:
  port: 9213

spring:
  application:
    name: sample-service-c

  # TODO 测试数据库
  #  datasource:
  #    platform: mysql
  #    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
  #    username: root
  #    password: root123

  cloud:
    loadbalancer:
      ribbon:
        enabled: true

  sleuth:
    sampler:
      # 采样比例1
      rate: 1
  zipkin:
    base-url: http://localhost:9411/

feign:
  hystrix:
    # TODO 暂时屏蔽
    enabled: false

ribbon:
  eager-load:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true