server:
  port: 8800

spring:
  application:
    # Dubbo 应用名称
    name: dubbo-spring-provider-1
#  main:
#    # Spring Boot 2.1 需要设定
#    allow-bean-definition-overriding: true

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: xyz.flysium.cloud.service
  cloud:
    subscribed-services:
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 28800
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  metadata-report:
    address:
