server:
  port: 9301

# 订阅消费的服务名
application.subscribe-provider.serviceId.serviceB: sample-seata-service-b
application.subscribe-provider.serviceId.serviceC: sample-seata-service-c

spring:
  application:
    name: sample-seata-service-a

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3307/seata_rm
    username: root
    password: root123

  cloud:
    loadbalancer:
      ribbon:
        enabled: true

    alibaba:
      seata:
        # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.my_tx_group
        tx-service-group: my_tx_group

ribbon:
  eager-load:
    enabled: true
    clients:
      - ${application.subscribe-provider.serviceId.serviceB}
      - ${application.subscribe-provider.serviceId.serviceC}

logging:
  level:
    xyz:
      flysium:
        repository: DEBUG

mybatis:
  type-aliases-package: xyz.flysium.dao.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

