spring:
  application:
    name: sample-ribbon-test-provider

  cloud:
    loadbalancer:
      ribbon:
        # TODO 暂时屏蔽
        enabled: false
feign:
  hystrix:
    # TODO 暂时屏蔽
    enabled: false

