server:
  port: 8761 #服务端口

spring:
  application:
    name: eureka-server-1 #指定服务名
#  security:
#      user:
#        name: root
#        password: root123

eureka:
  client:
    # 是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    # 是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://localhost:8761/eureka/
  #      defaultZone: http://root:root123@localhost:8761/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    # 服务名
    virtual-host-name: eureka-server
#    hostname: eureka01
