server:
  port: 9303

spring:
  application:
    name: sample-seata-service-c

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3309/seata_rm
    username: root
    password: root123

  cloud:
    alibaba:
      seata:
        # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.my_tx_group
        tx-service-group: my_tx_group

logging:
  level:
    xyz:
      flysium:
        repository: DEBUG

mybatis:
  type-aliases-package: xyz.flysium.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

