server:
  port: 1997

spring:
  application:
    name: sample-hystrix-test-provider

  cloud:
    loadbalancer:
      ribbon:
        enabled: true
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true