server:
  port: 8801

spring:
  application:
    # Dubbo 应用名称
    name: demo-consumer
#  main:
#    # Spring Boot 2.1 需要设定
#    allow-bean-definition-overriding: true

dubbo:
  cloud:
    subscribed-services: demo-provider-1
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: 28801
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  consumer:
    check: false
