server:
  port: 8800

# 暴露出来的服务名
register-provider:
  application:
    name: demo-provider-2

spring:
  application:
    # Dubbo 应用名称, dubbo 中协议 rest使用的服务名
    name: demo-provider-2
  # main:
  # Spring Boot 2.1 需要设定
  #   allow-bean-definition-overriding: true

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata

dubbo:
  application:
    name: ${spring.application.name}
  scan:
    # dubbo 服务扫描基准包
    base-packages: xyz.flysium.cloud.service
  cloud:
    subscribed-services: ${subscribe-provider.application.name}
  protocols:
    dubbo:
      name: dubbo
      # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
      port: 28801
    # none web 环境必须配置 rest 协议， web 环境不配置这个，改为配置 management.endpoints.web.exposure.include
  #    rest:
  #      name: rest
  #      port: 9090
  #      server: netty
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  #   address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

